### ISSUE TITLE
string "0" sent as an empty string

### ISSUE THREAD

**Issue by AmazingBeu** [maniaplanet/dedicated-server-api#37]
Using PHP 8.2, sending a string value `0` is transformed in an empty string. 

for example, it makes impossible to use the `Trackmania.SetTeamPoints` `triggerModeScriptEvent` to set points to the team 0.

It's due to this line:
https://github.com/maniaplanet/dedicated-server-api/blob/8d9d1d4bd6f4ae421746793a2ea1be60934ef83a/src/Maniaplanet/DedicatedServer/Xmlrpc/Request.php#L93

it's because PHP consider a string of `0` as false. Maybe you should just remove the check or be more precise like `$v === null`

I didn't test on previous versions of PHP.

**Comment by magnetik** [comment]
I've failed to do a MR but is https://github.com/maniaplanet/dedicated-server-api/commit/aeb06fd8d9184fb2dca46f96a8399735c8573b4d working for you? 

I went for the explicit way of doing things.

**Comment by AmazingBeu** [comment]
The `$value`variable doesn't exist, it is named `$v`. Except that, it works well!

**Comment by magnetik** [comment]
I've fixed it. I'll release 6.0.1
